# Generated by Django 5.0.1 on 2024-05-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('n_licence', models.DateField()),
                ('club', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to='images/')),
                ('netTiming', models.TimeField()),
                ('place', models.IntegerField(max_length=4, unique=True)),
            ],
        ),
    ]
